### ISSUE TITLE
ios兼容问题

### ISSUE THREAD

**Issue by shiwuyue** [ffx0s/xcrop#10]
裁剪框修改为允许收缩到裁剪框内部之后，会出现ios系统手机，裁剪完成之后是完全透明的情况。安卓手机正常

**Comment by ffx0s** [comment]
你好，没明白是什么意思，能否截个动图

**Comment by ffx0s** [comment]
@shiwuyue 你好，没明白是什么意思，能否截个动图

**Comment by shiwuyue** [comment]
苹果6录屏  
由于个人原因  除了苹果6，苹果6s之外其他手机存在的问题不好录屏。
苹果6图片正好的时候还能够裁剪下来，但是缩小一点则不行了。
而苹果8手机正方形图片正好铺满的情况都会存在下来为透明的情况。
图中上传完之后其实是透明的，白色是底色，请忽略。
[苹果6录屏.zip](https://github.com/ffx0s/xcrop/files/4868811/6.zip)

**Comment by shiwuyue** [comment]
[苹果8录屏.zip](https://github.com/ffx0s/xcrop/files/4868931/8.zip)
苹果8的录屏 可以看一下

**Comment by shiwuyue** [comment]
[苹果6sp录屏.zip](https://github.com/ffx0s/xcrop/files/4868945/6sp.zip)
苹果6sp的录屏可以看下

**Comment by ffx0s** [comment]
@shiwuyue `xcrop 1.1.15` 你用的是这个版本吗？

**Comment by shiwuyue** [comment]
嗯呢 是1.1.15的版本

**Comment by ffx0s** [comment]
@shiwuyue 能否贴一下你的调用代码、裁剪图片的尺寸还有系统的版本，我试了下复现不了这个 bug，这个问题我记得处理过，之前有人也反馈过这个问题。

**Comment by shiwuyue** [comment]
苹果6sp复现不了吗  随便上传一张都会有问题

**Comment by ffx0s** [comment]
@shiwuyue 是的，我手上只有 i7 真机，用 Simulator 测试了复现不了，用 example 测试的，因为不清楚你传了哪些参数，所以我用的都是默认裁剪选项。 看了你发的视频，双指缩放图片后，图片没有占满裁剪框后就会出现这个问题，因为之前处理过这个问题，解决方案是按确定裁剪按钮前再校验一次图片的位置好让它铺满裁剪框。如果你要实现允许图片不铺满裁剪框也可以裁剪的效果，可能你要自己改源码，或者换一个裁剪插件。

**Comment by xtyxl** [comment]
源代码里是修正了这个问题 ， 但是NPM源里拉到的版本内没有修正这个问题 。 
`if (clipX < 0) {
          clipX = 0;
        }

        var clipY = (crop.border.y * canvasRatio - y) / scale;

        if (clipY < 0) {
          clipY = 0;
        }`

**Comment by ffx0s** [comment]
@xtyxl  把你传的参数贴一下，我怎么测都测不出这个问题

**Comment by xtyxl** [comment]
> @xtyxl 把你传的参数贴一下，我怎么测都测不出这个问题

https://github.com/huixisheng/xcrop/commit/c8bd09c831089a6e50b171f67b8a53733e20cecc

其实就是这个问题。   NPM源里拉到的版本内没有修正这个问题， 重新修正， 换个版本号，再发布就行了。

**Comment by ffx0s** [comment]
@xtyxl 好了
