### ISSUE TITLE
Photos being rotated when cropping

### ISSUE THREAD

**Issue by yume-chan** [ffx0s/xcrop#14]
When cropping photos taken by mobile phones and cameras with EXIF orientation support, the photo was incorrectly rotated.

The reason is that, the `img` element in modern browsers already has built-in support for EXIF orientation information, and will rotate the image accordingly. So when xcrop reads EXIF orientation by itself and rotates the input, the image was rotated twice.

This behavior can be disabled by setting `image-orientation` style to `none` ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation), the default value is `from-image`, means "Use EXIF data from the image").

So my current workaround is something like:

```ts
const file = getFileWithSomeMethod();
const image = new Image();
image.style.imageOrientation = 'none';
image.onload = () => {
    crop.load(image);
};
image.src = window.URL.createObjectURL(file);
```

I think it should be added to here:

https://github.com/ffx0s/xcrop/blob/dd0c8bfb2af144683bcfa21806dc1b96382dd22c/src/util/image.js#L224-L236

I don't think we should disable `orientation` option in `imageToCanvas`, because some old browsers may not do this rotation. I didn't have enough devices to test.

**Comment by ffx0s** [comment]
Thank you for your feedback. I added this function to determine whether the browser supports auto-rotating pictures. If it supports rotation, xcrop will not rotate it again.
```javascript
function supportAutoOrientation (callback) {
  const testImageURL =
    'data:image/jpeg;base64,/9j/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAYAAAA' +
    'AAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA' +
    'QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE' +
    'BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIAAIAAwMBEQACEQEDEQH/x' +
    'ABRAAEAAAAAAAAAAAAAAAAAAAAKEAEBAQADAQEAAAAAAAAAAAAGBQQDCAkCBwEBAAAAAAA' +
    'AAAAAAAAAAAAAABEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AG8T9NfSMEVMhQ' +
    'voP3fFiRZ+MTHDifa/95OFSZU5OzRzxkyejv8ciEfhSceSXGjS8eSdLnZc2HDm4M3BxcXw' +
    'H/9k='
  const img = document.createElement('img')
  img.onload = function () {
    const orientation = img.width === 2 && img.height === 3
    callback(orientation)
  }
  img.src = testImageURL
}
```
