### ISSUE TITLE
ios 图片移动超出裁剪区域后再裁剪出现黑屏

### ISSUE THREAD

**Issue by huixisheng** [ffx0s/xcrop#5]
![image](https://user-images.githubusercontent.com/1518967/64190433-f6166080-cea8-11e9-8572-62cf9832ae41.png)

**Comment by ffx0s** [comment]
IOS 下调用 drawImage(canvas, x, y,  w, h, ...) 会有问题，其它平台正常，貌似是个兼容性问题😂。所以现在是直接在裁剪前先判断是否超出裁剪范围，超出了则修正图片位置后再裁剪。
